version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo "Building the Spring Boot project..."
      - chmod +x ./gradlew
      - ./gradlew clean build -x test
artifacts:
  files:
    - build/libs/*.jar
    - appspec.yml        # (추가) 배포 설명서 챙기기
    - scripts/**         # (추가) 실행 스크립트 챙기기
  discard-paths: no      # (수정) 폴더 구조 유지하기 (yes -> no)